spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grpc-product-spring-api-database
    username: eduardo
    password: root
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
